stages:
  - build

docker-image:
  stage: build
  tags: [homelab-runner]
  variables:
    IMAGE_LATEST: "$CI_REGISTRY_IMAGE:latest"
    IMAGE_SHA: "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA"
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - docker build --pull --provenance=false -f docker/Dockerfile -t "$IMAGE_LATEST" -t "$IMAGE_SHA" .
    - docker push "$IMAGE_LATEST"
    - docker push "$IMAGE_SHA"
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'

docker-release:
  stage: build
  tags: [homelab-runner]
  variables:
    IMAGE_RELEASE: "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG"
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - docker build --pull --provenance=false -f docker/Dockerfile -t "$IMAGE_RELEASE" .
    - docker push "$IMAGE_RELEASE"
  rules:
    - if: '$CI_COMMIT_TAG'
